# Buildkite pipeline for kuberwatcher.
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-kuberwatcher
  description: Buildkite Pipeline for kuberwatcher

spec:
  type: buildkite-pipeline
  owner: group:infra-services
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: kuberwatcher
    spec:
      repository: elastic/kuberwatcher
      pipeline_file: ".buildkite/pipeline.yml"
      provider_settings:
        build_pull_requests: true
        build_pull_request_ready_for_review: true
        publish_commit_status: true
        publish_commit_status_per_step: false
        publish_blocked_as_pending: true
        skip_pull_request_builds_for_existing_commits: true
        cancel_deleted_branch_builds: true
      teams:
        infra-services:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY